insert into CUSTOMERS (CUSTOMER_NAME, EMAIL, PASSWORD) VALUES ('admin', 'admin@admin.com', 'admin');
insert into CUSTOMERS (CUSTOMER_NAME, EMAIL, PASSWORD) VALUES ('Bruce', 'bruce@a.com', 'password1');
insert into CUSTOMERS (CUSTOMER_NAME, EMAIL, PASSWORD) VALUES ('Paul', 'paul@b.com', 'password2');
insert into CUSTOMERS (CUSTOMER_NAME, EMAIL, PASSWORD) VALUES ('Rick', 'rick@c.com', 'password3');
insert into REGISTRATIONS (CUSTOMER_ID, EVENT_ID, REGISTRATION_DATE) VALUES (1, 1, CURRENT_TIMESTAMP());
insert into REGISTRATIONS (CUSTOMER_ID, EVENT_ID, REGISTRATION_DATE) VALUES (2, 2, CURRENT_TIMESTAMP());