insert into CUSTOMERS (CUSTOMER_NAME, EMAIL, PASSWORD) VALUES ('admin', 'admin@admin.com', 'admin');
insert into CUSTOMERS (CUSTOMER_NAME, EMAIL, PASSWORD) VALUES ('Bruce', 'bruce@a.com', 'password1');
insert into CUSTOMERS (CUSTOMER_NAME, EMAIL, PASSWORD) VALUES ('Paul', 'paul@b.com', 'password2');
insert into CUSTOMERS (CUSTOMER_NAME, EMAIL, PASSWORD) VALUES ('Rick', 'rick@c.com', 'password3');

insert into EVENTS (EVENT_NAME, EVENT_DATE, LOCATION) VALUES ('Spring Festival', '2024-05-01', 'Central Park');
insert into EVENTS (EVENT_NAME, EVENT_DATE, LOCATION) VALUES ('Tech Conference', '2024-06-15', 'Convention Center');
insert into EVENTS (EVENT_NAME, EVENT_DATE, LOCATION) VALUES ('Music Concert', '2024-07-20', 'Downtown Arena'); 
insert into EVENTS (EVENT_NAME, EVENT_DATE, LOCATION) VALUES ('Art Exhibition', '2024-08-05', 'City Gallery');

INSERT INTO REGISTRATIONS (CUSTOMER_ID, EVENT_ID, REGISTRATION_DATE, STATUS) VALUES (1, 1, CURRENT_TIMESTAMP(), 'CONFIRMED');
INSERT INTO REGISTRATIONS (CUSTOMER_ID, EVENT_ID, REGISTRATION_DATE, STATUS) VALUES (2, 2, CURRENT_TIMESTAMP(), 'CONFIRMED');
INSERT INTO REGISTRATIONS (CUSTOMER_ID, EVENT_ID, REGISTRATION_DATE, STATUS) VALUES (3, 3, CURRENT_TIMESTAMP(), 'CONFIRMED');
INSERT INTO REGISTRATIONS (CUSTOMER_ID, EVENT_ID, REGISTRATION_DATE, STATUS) VALUES (4, 4, CURRENT_TIMESTAMP(), 'CONFIRMED');
INSERT INTO REGISTRATIONS (CUSTOMER_ID, EVENT_ID, REGISTRATION_DATE, STATUS) VALUES (1, 2, CURRENT_TIMESTAMP(), 'CONFIRMED');
INSERT INTO REGISTRATIONS (CUSTOMER_ID, EVENT_ID, REGISTRATION_DATE, STATUS) VALUES (2, 3, CURRENT_TIMESTAMP(), 'CONFIRMED');
