-- Customer table (for login/authentication)
DROP TABLE IF EXISTS registrations;
DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS customers;
DROP TABLE IF EXISTS events;

CREATE TABLE "CUSTOMERS" (
    "ID" INTEGER AUTO_INCREMENT PRIMARY KEY, 
    "CUSTOMER_NAME" VARCHAR(255), 
    "EMAIL" VARCHAR(255),
    "PASSWORD" VARCHAR(255),
    PRIMARY KEY ("ID")
);

DROP TABLE IF EXISTS events;
CREATE TABLE "EVENTS" (
    "ID" INTEGER AUTO_INCREMENT PRIMARY KEY, 
    "EVENT_NAME" VARCHAR(255), 
    "EVENT_DATE" DATE,
    "LOCATION" VARCHAR(255),
    PRIMARY KEY ("ID")
);

CREATE TABLE "REGISTRATIONS" (
    "ID" INTEGER AUTO_INCREMENT PRIMARY KEY, 
    "CUSTOMER_ID" INTEGER,
    "EVENT_ID" INTEGER,
    "REGISTRATION_DATE" TIMESTAMP,
    "STATUS" VARCHAR(50),
    PRIMARY KEY ("ID"),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID) ON DELETE CASCADE,
    FOREIGN KEY (EVENT_ID) REFERENCES EVENTS(ID) ON DELETE CASCADE,
    UNIQUE(CUSTOMER_ID, EVENT_ID)
)
