-- Customer table (for login/authentication)
DROP TABLE IF EXISTS customers;

CREATE TABLE "CUSTOMERS" (
    "ID" INTEGER AUTO_INCREMENT PRIMARY KEY, 
    "CUSTOMER_NAME" VARCHAR(255), 
    "EMAIL" VARCHAR(255),
    "PASSWORD" VARCHAR(255),
    PRIMARY KEY ("ID")
);
